services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=support_user
      - POSTGRES_PASSWORD=support_user
      - POSTGRES_DB=supportdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: Initialize database with scripts
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: